// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkdzm8HTv39QkpR88jGQSy9Jnosewd2m8',
    appId: '1:695641327682:web:91019e6c0cef0f4fc205db',
    messagingSenderId: '695641327682',
    projectId: 'home-chef-3q2zof',
    authDomain: 'home-chef-3q2zof.firebaseapp.com',
    storageBucket: 'home-chef-3q2zof.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeS6YfEcU-R1StW_GZS8fy2ySAl_YTjKk',
    appId: '1:695641327682:android:7d65ff49aa927a4fc205db',
    messagingSenderId: '695641327682',
    projectId: 'home-chef-3q2zof',
    storageBucket: 'home-chef-3q2zof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOWLSTdGevaofMgE0g4dh7Qw8EkH6fW3c',
    appId: '1:695641327682:ios:c78cd2bc43b160bbc205db',
    messagingSenderId: '695641327682',
    projectId: 'home-chef-3q2zof',
    storageBucket: 'home-chef-3q2zof.appspot.com',
    iosClientId: '695641327682-acvlhcb87ggd8jeavla951cqbcnj9ftb.apps.googleusercontent.com',
    iosBundleId: 'com.example.souschef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOWLSTdGevaofMgE0g4dh7Qw8EkH6fW3c',
    appId: '1:695641327682:ios:c78cd2bc43b160bbc205db',
    messagingSenderId: '695641327682',
    projectId: 'home-chef-3q2zof',
    storageBucket: 'home-chef-3q2zof.appspot.com',
    iosClientId: '695641327682-acvlhcb87ggd8jeavla951cqbcnj9ftb.apps.googleusercontent.com',
    iosBundleId: 'com.example.souschef',
  );
}
